import test from 'node:test';import assert from 'node:assert/strict';import {registerHooks} from 'node:module';
import {buildTitlePreview,etsyTitle,titleApplySchema,safeTitleError} from '../lib/warlock-commerce/etsy-listing-title.ts';
const db={product:null,journals:[],remote:null,writes:0,mode:true,unknown:false,failFinalize:false};globalThis.__titleDb=db;
function setup(state='active',fulfillment='DIGITAL'){
 db.product={id:'p',title:'Internal artwork name',description:'Product copy',assets:[],variants:[],listings:[{id:'l',fulfillment,etsyListingId:'20',title:'Old canonical title',description:'Required disclosure',tagsJson:'["keep"]',status:'DRAFT_CREATED',lastVerifiedAt:'old',observationJson:'old',assets:[]}]};
 db.remote={listing_id:20,shop_id:99,state,listing_type:fulfillment==='DIGITAL'?'download':'physical',title:'Old Etsy title',description:'Remote disclosure',tags:['keep'],quantity:10,taxonomy_id:123,price:{amount:4900,divisor:100,currency_code:'USD'},last_modified_timestamp:1};db.journals=[];db.writes=0;db.mode=true;db.unknown=false;db.failFinalize=false;
 return {productId:'p',fulfillment,expectedEtsyListingId:'20',newTitle:'Botanical Digital Art Print'};
}
db.spellmarkJournal={findFirst:async({where})=>structuredClone(db.journals.find(j=>Object.entries(where).every(([k,v])=>j[k]===v))??null),findUnique:async({where})=>structuredClone(db.journals.find(j=>j.productId===where.productId_requestId.productId&&j.requestId===where.productId_requestId.requestId)??null),create:async({data})=>{const j={id:'journal-'+db.journals.length,...data};db.journals.push(j);return j;},update:async({where,data})=>{if(db.failFinalize&&JSON.parse(data.bodyJson).state==='TITLE_VERIFIED')throw Error('db failure');Object.assign(db.journals.find(j=>j.requestId===where.productId_requestId.requestId),data);}};
db.spellmarkListing={update:async({data})=>Object.assign(db.product.listings[0],data)};db.$queryRaw=async()=>[];
db.$transaction=async fn=>{const before=structuredClone({product:db.product,journals:db.journals});try{return await fn(db);}catch(e){Object.assign(db,before);throw e;}};
const hooks=registerHooks({resolve(s,c,next){if(c.parentURL?.endsWith('/etsy-title-executor.ts')){const stubs={'../prisma':'export const prisma=globalThis.__titleDb;','../warlock-mcp/repository':'export async function findWarlockProduct(){return structuredClone(globalThis.__titleDb.product);}','../warlock-auth':'export async function getWarlockEtsyOperatorContext(){return {shopId:99,auth:{session:{access_token:"test"}}};}','./etsy-reconciliation-read':'export async function readEtsyForReconciliation(){return structuredClone(globalThis.__titleDb.remote);}','./etsy-title-transport':'export async function writeEtsyTitle(_token,_shop,_id,title){const d=globalThis.__titleDb;const intent=JSON.parse(d.journals.find(j=>j.kind==="ETSY_TITLE_CHANGE").bodyJson);if(intent.state!=="SENDING"||d.product.listings[0].title!==title)throw Error("intent not durable");d.writes++;d.remote.title=title;d.remote.last_modified_timestamp++;if(d.unknown)throw Error("network failure");}','./write-guard.ts':'export function assertCommerceDraftWritesEnabled(){if(!globalThis.__titleDb.mode)throw Error("warlock_commerce_writes_disabled");}'};if(stubs[s])return {url:'data:text/javascript,'+encodeURIComponent(stubs[s]),shortCircuit:true};}return next(s,c);}});
const {previewEtsyListingTitle,applyEtsyListingTitle}=await import('../lib/warlock-commerce/etsy-title-executor.ts');hooks.deregister();
test('title validation enforces exact API characters and limits without truncation',()=>{for(const s of ['', ' x','x\n','x'.repeat(141),'Two & three & four','Emoji 🌙'])assert.equal(etsyTitle.safeParse(s).success,false);assert.equal(etsyTitle.safeParse('Sol & Luna — Digital Art Print').success,true);assert.throws(()=>titleApplySchema.parse({productId:'p',previewId:'x',confirmTitleChange:false}));assert.equal(safeTitleError(Error('secret token')),'etsy_title_edit_failed');});
test('preview shows canonical/remote/proposed titles and active state without edits',async()=>{const input=setup();const before=structuredClone(db.product),p=await previewEtsyListingTitle(input);assert.equal(p.preview.canonicalTitle,'Old canonical title');assert.equal(p.preview.remote.title,'Old Etsy title');assert.equal(p.preview.remote.state,'active');assert.equal(p.preview.input.newTitle,input.newTitle);assert.deepEqual(db.product,before);assert.equal(db.writes,0);});
test('active digital and draft physical apply save intent first and verify only title changes',async()=>{for(const [state,fulfillment] of [['active','DIGITAL'],['draft','PHYSICAL']]){const input=setup(state,fulfillment),before=structuredClone(db.product),remoteBefore=structuredClone(db.remote),p=await previewEtsyListingTitle(input),r=await applyEtsyListingTitle({productId:'p',previewId:p.previewId,confirmTitleChange:true});assert.equal(r.state,'TITLE_VERIFIED');assert.equal(r.published,false);assert.equal(db.writes,1);assert.equal(db.product.title,before.title);assert.equal(db.product.listings[0].description,before.listings[0].description);assert.equal(db.remote.state,state);assert.equal(db.remote.description,remoteBefore.description);assert.equal(db.remote.quantity,10);assert.equal(db.product.listings[0].title,input.newTitle);const retry=await applyEtsyListingTitle({productId:'p',previewId:p.previewId,confirmTitleChange:true});assert.equal(retry.reused,true);assert.equal(db.writes,1);}});
test('canonical-only convergence does not claim an Etsy write',async()=>{const input=setup();db.remote.title=input.newTitle;const p=await previewEtsyListingTitle(input);const r=await applyEtsyListingTitle({productId:'p',previewId:p.previewId,confirmTitleChange:true});assert.equal(r.state,'TITLE_VERIFIED');assert.equal(r.etsyMutated,false);assert.equal(db.writes,0);});
test('ownership/state/type mismatches cannot produce an approval preview',async()=>{for(const [key,value] of [['shop_id',100],['listing_id',21],['state','inactive'],['listing_type','physical']]){const input=setup();db.remote[key]=value;await assert.rejects(previewEtsyListingTitle(input));assert.equal(db.writes,0);}});
test('disabled writes, expired approval, canonical and remote drift refuse mutation',async()=>{for(const mutate of [()=>db.mode=false,()=>db.product.listings[0].title='changed',()=>db.remote.title='changed',()=>{const j=db.journals[0],p=JSON.parse(j.bodyJson);p.expiresAt=new Date(0).toISOString();j.bodyJson=JSON.stringify(p);}]){const input=setup(),p=await previewEtsyListingTitle(input);mutate();await assert.rejects(applyEtsyListingTitle({productId:'p',previewId:p.previewId,confirmTitleChange:true}));assert.equal(db.writes,0);assert.equal(db.journals.filter(j=>j.kind==='ETSY_TITLE_CHANGE').length,0);}});
test('unknown network outcome persists intent; retry verifies and never repeats PATCH',async()=>{const input=setup(),p=await previewEtsyListingTitle(input);db.unknown=true;const r=await applyEtsyListingTitle({productId:'p',previewId:p.previewId,confirmTitleChange:true});assert.equal(r.state,'NEEDS_REVIEW');assert.equal(JSON.parse(db.journals[1].bodyJson).state,'SENDING');assert.equal(db.product.listings[0].title,input.newTitle);const retry=await applyEtsyListingTitle({productId:'p',previewId:p.previewId,confirmTitleChange:true});assert.equal(retry.state,'TITLE_VERIFIED');assert.equal(db.writes,1);});
test('post-write database rollback keeps durable SENDING evidence and supports read-only recovery',async()=>{const input=setup(),p=await previewEtsyListingTitle(input);db.failFinalize=true;const r=await applyEtsyListingTitle({productId:'p',previewId:p.previewId,confirmTitleChange:true});assert.equal(r.state,'NEEDS_REVIEW');assert.equal(db.remote.title,input.newTitle);assert.equal(JSON.parse(db.journals[1].bodyJson).state,'SENDING');db.failFinalize=false;const retry=await applyEtsyListingTitle({productId:'p',previewId:p.previewId,confirmTitleChange:true});assert.equal(retry.state,'TITLE_VERIFIED');assert.equal(db.writes,1);});
test('uncertain old or independently changed remote state never gets replayed',async()=>{const input=setup(),p=await previewEtsyListingTitle(input);db.unknown=true;await applyEtsyListingTitle({productId:'p',previewId:p.previewId,confirmTitleChange:true});db.remote.title='Old Etsy title';const retry=await applyEtsyListingTitle({productId:'p',previewId:p.previewId,confirmTitleChange:true});assert.equal(retry.state,'NEEDS_REVIEW');assert.equal(db.writes,1);});
// Exercise actual narrow HTTP transport separately.
const transportHooks=registerHooks({resolve(s,c,next){if(c.parentURL?.endsWith('/etsy-title-transport.ts')&&s==='../etsy-client')return {url:'data:text/javascript,export function etsyHeaders(){return {Authorization:"Bearer test"}}',shortCircuit:true};return next(s,c);}});const {writeEtsyTitle}=await import('../lib/warlock-commerce/etsy-title-transport.ts');transportHooks.deregister();
test('title transport sends only the title form key to the existing shop listing PATCH',async()=>{const saved=globalThis.fetch;let req;globalThis.fetch=async(url,args)=>{req={url,args};return new Response('{}',{status:200});};try{await writeEtsyTitle('test',99,'20','Clear Digital Art Print');assert.equal(req.args.method,'PATCH');assert.equal(req.url,'https://api.etsy.com/v3/application/shops/99/listings/20');assert.deepEqual([...req.args.body.keys()],['title']);assert.equal(req.args.body.get('title'),'Clear Digital Art Print');}finally{globalThis.fetch=saved;}});
