import test from 'node:test';
import assert from 'node:assert/strict';
import {buildGarmentPreview,applyGarmentPreview,readMigrationTarget,validateMigrationAvailability,inspectUnchangedMigrationSource,classifyGarmentMigration,reactivateGarmentPreview,garmentEnableShape,garmentPreviewSchema,garmentApplyShape} from '../lib/warlock-commerce/garment-migration.ts';
import {configureImportedPrintful} from '../lib/warlock-commerce/printful-sync-service.ts';
import * as z from 'zod/v4';
function fixture(){
 const manifest={id:'p1',assets:[],listings:[{id:'l1',title:'Approved artwork',fulfillment:'PHYSICAL',etsyListingId:'123',printfulSyncProductId:101,status:'SYNCED',description:'Old garment description',assets:[],taxonomyId:1,shippingProfileId:'9',readinessStateId:'7'},{id:'digital',title:'Digital',description:'Digital description',fulfillment:'DIGITAL',etsyListingId:'999',assets:[]}],variants:[1,2].map(n=>({id:'v'+n,label:n===1?'Black / M':'Carbon Grey / M',fulfillment:'PHYSICAL',currency:'USD',retailPriceCents:6000,printfulProductId:411,printfulVariantId:900+n,printfulStoreId:99,printfulSyncVariantId:300+n,etsyListingId:'123',etsyProductId:String(100+n),etsySku:'SM-'+n})).concat({id:'d1',fulfillment:'DIGITAL',currency:'USD',retailPriceCents:400})};
 const listing={listing_id:123,shop_id:9,state:'active',listing_type:'physical',title:'Approved artwork',description:'Old garment description',tags:['art'],taxonomy_id:1,shipping_profile_id:9};
 let inventory={products:manifest.variants.filter(v=>v.fulfillment==='PHYSICAL').map((v,i)=>({product_id:101+i,sku:v.etsySku,is_deleted:false,property_values:[{property_id:513,property_name:'Edition',scale_id:null,value_ids:[11+i],values:[v.label]}],offerings:[{offering_id:201+i,is_deleted:false,quantity:999,is_enabled:true,readiness_state_id:7,price:{amount:6000,divisor:100,currency_code:'USD'}}]})),price_on_property:[513],quantity_on_property:[],sku_on_property:[513],readiness_state_on_property:[]};
 const colors=['Black','Heather Grey','Dark Heather'];const calls=[];let saved;
 const read=async path=>{calls.push({kind:'read',path});return structuredClone(path.includes('/inventory')?inventory:listing)};
 const get=async path=>{
  if(path==='/stores')return {result:[{id:99}]};const id=Number(path.match(/(?:variant\/|catalog-variants\/)(\d+)/)?.[1]);
  if(path.startsWith('/products/variant/'))return {result:{variant:{id,product_id:71,color:colors[id-4011],size:'M'},product:{id:71,techniques:[{key:'dtg',is_default:true}],files:[{id:'default',type:'front',additional_price:null}]}}};
  if(path.includes('/prices'))return {data:{currency:'USD',variant:{id,techniques:[{technique_key:'dtg',price:'12.00'}]},product:{id:71,placements:[{id:'front',technique_key:'dtg',layers:[{type:'file',additional_price:'0.00'}]}]}}};
  if(path.includes('/availability'))return {data:{techniques:[{technique:'dtg',selling_regions:[{name:'north_america',availability:'in stock'}]}]}};
  throw Error('unexpected '+path);
 };
 const input={productId:'p1',description:'Approved new Gildan garment description',targets:[{sourceVariantId:'v1',variantId:'v1',catalogProductId:71,catalogVariantId:4011,color:'Black',size:'M'},{sourceVariantId:'v2',variantId:'v2',catalogProductId:71,catalogVariantId:4012,color:'Heather Grey',size:'M'},{sourceVariantId:'v2',catalogProductId:71,catalogVariantId:4013,color:'Dark Heather',size:'M'}]};
 const deps={read,recordIntent:async phase=>calls.push({kind:'intent',phase}),writeState:async(id,state)=>{calls.push({kind:'state',id,state});listing.state=state;},writeInventory:async(id,body)=>{calls.push({kind:'inventory',id,body});inventory={...structuredClone(body),products:body.products.map((p,i)=>({...structuredClone(p),product_id:1001+i,is_deleted:false,property_values:p.property_values.map(v=>({...v,value_ids:[51+i]})),offerings:p.offerings.map(o=>({...o,offering_id:2001+i,is_deleted:false,price:{amount:Math.round(o.price*100),divisor:100,currency_code:'USD'}}))}))};},writeDescription:async(id,description)=>{calls.push({kind:'description',id,description});listing.description=description;},save:async mapped=>{calls.push({kind:'save'});saved=mapped;}};
 return {manifest,listing,input,read,get,calls,deps,get inventory(){return inventory},get saved(){return saved},set inventory(v){inventory=v}};
}
async function setup(){const f=fixture(),p=await buildGarmentPreview(f.manifest,f.input,9,f.read,f.get,'op-test');return {f,p};}
const writes=f=>f.calls.filter(c=>['state','inventory','description'].includes(c.kind));
test('saved preview adds catalog colors while retaining IDs, prices, quantities and digital editions',async()=>{const f=fixture(),original=structuredClone(f.manifest),p=await buildGarmentPreview(f.manifest,f.input,9,f.read,f.get,'op-test');assert.equal(p.targets.length,3);assert.equal(p.targets[0].variantId,'v1');assert.equal(p.targets[2].isNew,true);assert.equal(p.targets[2].retailPriceCents,6000);assert.ok(p.desired.products.every(p=>p.offerings[0].is_enabled&&p.offerings[0].quantity===999&&p.offerings[0].price===60));assert.ok(p.description.includes('AI-assisted image-making'));assert.deepEqual(f.manifest,original);assert.equal(writes(f).length,0)});
test('apply first deactivates the existing listing then writes valid inventory and description, verifies new Etsy IDs before canonical save',async()=>{const {f,p}=await setup(),original=structuredClone(f.manifest);const result=await applyGarmentPreview(f.manifest,p,f.deps);assert.equal(result.state,'GARMENT_MIGRATION_STAGED');assert.equal(result.editionsAvailable,false);assert.deepEqual(writes(f).map(c=>c.kind),['state','inventory','description']);assert.equal(f.calls.findIndex(c=>c.kind==='intent')<f.calls.findIndex(c=>c.kind==='inventory'),true);assert.equal(f.saved[0].etsyProductId,'1001');assert.equal(f.saved[2].etsySku,p.targets[2].sku);assert.equal(f.calls.at(-1).kind,'save');assert.deepEqual(f.manifest,original);assert.equal(f.listing.state,'inactive');assert.equal(f.listing.title,'Approved artwork')});
test('foreign, missing, duplicated editions and incorrect catalog colors are rejected',async()=>{for(const mutate of [i=>i.targets[0].sourceVariantId='foreign',i=>i.targets[0].variantId=undefined,i=>i.targets[2].variantId='v2',i=>i.targets[1].color='Unverified Heather',i=>i.targets[2].catalogVariantId=4012]){const f=fixture();mutate(f.input);await assert.rejects(buildGarmentPreview(f.manifest,f.input,9,f.read,f.get,'op-test'));assert.equal(writes(f).length,0)}});
test('ownership, unsupported listing type, disabled source and price drift block preview',async()=>{for(const mutate of [f=>f.listing.shop_id=10,f=>f.listing.listing_type='download',f=>f.inventory.products[0].offerings[0].is_enabled=false,f=>f.inventory.products[0].offerings[0].price.amount=6100]){const f=fixture();mutate(f);await assert.rejects(buildGarmentPreview(f.manifest,f.input,9,f.read,f.get,'op-test'));assert.equal(writes(f).length,0)}});
test('changed canonical fields, description, inventory and expired preview reject all writes',async()=>{for(const mutate of [(f,p)=>f.manifest.variants[0].retailPriceCents=6200,(f,p)=>f.listing.description='External change',(f,p)=>f.inventory.products[0].offerings[0].quantity=3,(f,p)=>p.expiresAt='2020-01-01',(f,p)=>f.listing.title='Changed title']){const {f,p}=await setup();mutate(f,p);await assert.rejects(applyGarmentPreview(f.manifest,p,f.deps));assert.equal(writes(f).length,0)}});
test('recovery verifies uncertain applied inventory without repeating its PUT',async()=>{const {f,p}=await setup();const put=f.deps.writeInventory;f.deps.writeInventory=async(...args)=>{await put(...args);throw Error('timeout after save')};await assert.rejects(applyGarmentPreview(f.manifest,p,f.deps));assert.equal(writes(f).length,2);f.deps.writeInventory=put;const result=await applyGarmentPreview(f.manifest,p,f.deps,true);assert.equal(result.state,'GARMENT_MIGRATION_STAGED');assert.equal(f.calls.filter(c=>c.kind==='inventory').length,1);assert.equal(f.calls.filter(c=>c.kind==='description').length,1)});
test('uncertain outcome without saved target requires inspection and never repeats inventory upload',async()=>{const {f,p}=await setup();await assert.rejects(applyGarmentPreview(f.manifest,p,f.deps,true),/uncertain_inventory/);assert.equal(writes(f).length,0)});
test('unexpected target quantities or unrelated listing edits stop before canonical finalization',async()=>{const {f,p}=await setup();const put=f.deps.writeInventory;f.deps.writeInventory=async(...args)=>{await put(...args);f.inventory.products[0].offerings[0].quantity=5};await assert.rejects(applyGarmentPreview(f.manifest,p,f.deps),/target_not_saved/);assert.equal(f.saved,undefined);assert.equal(f.calls.filter(c=>c.kind==='description').length,0)});
test('inventory mutation requires explicit temporary unavailability confirmation',()=>{assert.equal(z.strictObject(garmentApplyShape).safeParse({productId:'p1',previewId:'preview',confirmMigration:true}).success,false);assert.equal(garmentPreviewSchema.safeParse({productId:'p1',description:'new',targets:[]}).success,false)});
test('automatic default Printful configuration cannot clear pending migration or upload old artwork',async()=>{const f=fixture();f.manifest.listings[0].status='MIGRATION_PENDING';const r=await configureImportedPrintful(f.manifest,{request:async()=>assert.fail('no supplier request'),saveListing:async()=>assert.fail('no status write'),saveVariant:async()=>assert.fail('no variant write'),temporaryAsset:async()=>assert.fail('no upload')});assert.equal(r.errorCode,'printful_garment_migration_placements_required')});
test('enabling requires evidence for all new editions, configured quotes, and combined margin',async()=>{const {f,p}=await setup();const m={...f.manifest,variants:p.targets.map(t=>({...f.manifest.variants.find(v=>v.id===t.sourceVariantId),id:t.variantId,label:t.label,etsySku:t.sku,printfulProductId:t.catalogProductId,printfulVariantId:t.catalogVariantId,printfulSyncVariantId:301,productionQuoteJson:JSON.stringify({configurationKind:'CONFIGURED_SYNC'})}))};const evidence={state:'PLACEMENT_FILES_VERIFIED',verifiedVariantIds:p.targets.map(t=>t.variantId)};const supplier={pass:true,variants:p.targets.map(t=>({variantId:t.variantId,quote:{...t.quote,configurationKind:'CONFIGURED_SYNC',productionBaseCents:1800}}))};assert.ok(validateMigrationAvailability(m,p,evidence,supplier));assert.throws(()=>validateMigrationAvailability(m,p,{...evidence,verifiedVariantIds:['v1']},supplier),/placement_verification/);assert.throws(()=>validateMigrationAvailability(m,p,evidence,{...supplier,pass:false}),/supplier_not_verified/);const costly=structuredClone(supplier);costly.variants.forEach(v=>v.quote.productionBaseCents=5990);assert.throws(()=>validateMigrationAvailability(m,p,evidence,costly),/combined_margin/)});

test('unchanged-source inspection resolves legacy failed attempts without any external writes',async()=>{const {f,p}=await setup();p.expiresAt='2020-01-01';const r=await inspectUnchangedMigrationSource(f.manifest,p,f.read);assert.equal(r.state,'GARMENT_MIGRATION_SOURCE_UNCHANGED');assert.equal(r.inventoryFingerprint,p.beforeInventoryFingerprint);assert.equal(r.editionsAvailable,true);assert.equal(writes(f).length,0)});
test('source resolution rejects partial application and every protected-field or inventory drift',async()=>{for(const mutate of [f=>f.listing.shop_id=10,f=>f.listing.state='inactive',f=>f.listing.description='Changed',f=>f.listing.tags=['Changed'],f=>f.inventory.products[0].offerings[0].is_enabled=false,f=>f.inventory.products[0].offerings[0].quantity=2,f=>f.inventory.products[0].offerings[0].price.amount=5900,f=>f.inventory.products[0].property_values[0].values=['New'],f=>f.manifest.variants[0].printfulVariantId=4011]){const {f,p}=await setup();mutate(f);await assert.rejects(inspectUnchangedMigrationSource(f.manifest,p,f.read));assert.equal(writes(f).length,0)}});
test('saved target cannot be misclassified as an unchanged source',async()=>{const {f,p}=await setup();f.listing.state='inactive';await f.deps.writeInventory('123',p.desired);await assert.rejects(inspectUnchangedMigrationSource(f.manifest,p,f.read));assert.equal(writes(f).length,1)});

test('Etsy-like validator accepts migration because all-disabled inventory is never submitted',async()=>{const {f,p}=await setup();const put=f.deps.writeInventory;f.deps.writeInventory=async(...args)=>{assert.equal(f.listing.state,'inactive');assert.ok(args[1].products.some(v=>v.offerings[0].is_enabled),'One offering must be enabled');return put(...args)};await applyGarmentPreview(f.manifest,p,f.deps);assert.equal(f.calls.filter(c=>c.kind==='state').length,1);assert.ok(f.calls.filter(c=>c.kind==='state').every(c=>c.state==='inactive'));assert.equal(f.listing.state,'inactive')});
test('deactivation rejection or unverified state prevents every inventory and description write',async()=>{for(const failure of [async()=>{throw Error('etsy_http_400')},async()=>{}]){const {f,p}=await setup();f.deps.writeState=failure;await assert.rejects(applyGarmentPreview(f.manifest,p,f.deps));assert.equal(f.calls.filter(c=>['inventory','description','save'].includes(c.kind)).length,0)}});
test('deactivation timeout readback can resume without replaying state changes',async()=>{const {f,p}=await setup();const patch=f.deps.writeState;f.deps.writeState=async(...args)=>{await patch(...args);throw Error('timeout')};await assert.rejects(applyGarmentPreview(f.manifest,p,f.deps));assert.equal(f.listing.state,'inactive');f.deps.writeState=patch;await applyGarmentPreview(f.manifest,p,f.deps,'DEACTIVATION_STARTED');assert.equal(f.calls.filter(c=>c.kind==='state').length,1);assert.equal(f.calls.filter(c=>c.kind==='inventory').length,1)});
test('uncertain inventory on inactive source requires explicit resolution before reissue',async()=>{const {f,p}=await setup();f.listing.state='inactive';await assert.rejects(applyGarmentPreview(f.manifest,p,f.deps,'INVENTORY_STARTED'),/uncertain_inventory/);assert.equal(writes(f).length,0);const r=await inspectUnchangedMigrationSource(f.manifest,p,f.read,true);assert.equal(r.state,'GARMENT_MIGRATION_DEACTIVATED_SOURCE_UNCHANGED');assert.equal(r.editionsAvailable,false);await applyGarmentPreview(f.manifest,p,f.deps,'DEACTIVATION_VERIFIED');assert.equal(f.calls.filter(c=>c.kind==='state').length,0);assert.equal(f.calls.filter(c=>c.kind==='inventory').length,1)});
test('legacy all-disabled previews are not reinterpreted as approved deactivation',async()=>{const {f,p}=await setup();p.schemaVersion=1;await assert.rejects(applyGarmentPreview(f.manifest,p,f.deps),/fresh_preview_required/);assert.equal(writes(f).length,0)});
test('deactivation and existing-listing reactivation need distinct explicit confirmations',()=>{const apply={productId:'p',previewId:'pv',confirmMigration:true,confirmTemporaryUnavailability:true};assert.equal(z.strictObject(garmentApplyShape).safeParse(apply).success,false);assert.equal(z.strictObject(garmentApplyShape).safeParse({...apply,confirmTemporaryDeactivation:true}).success,true);const enable={productId:'p',previewId:'pv',expectedInventoryFingerprint:'a'.repeat(64),confirmVisualReview:true,confirmAvailability:true};assert.equal(z.strictObject(garmentEnableShape).safeParse(enable).success,false);assert.equal(z.strictObject(garmentEnableShape).safeParse({...enable,confirmExistingListingReactivation:true}).success,true)});
test('confirmed reactivation changes only the existing listing state and retries without further PATCH',async()=>{const {f,p}=await setup();const staged=await applyGarmentPreview(f.manifest,p,f.deps);const before=structuredClone(f.inventory);f.calls.length=0;const result=await reactivateGarmentPreview(p,f.read,f.deps.writeState,staged.inventoryFingerprint,true);assert.equal(result.existingListingReactivated,true);assert.equal(f.listing.state,'active');assert.deepEqual(f.inventory,before);assert.deepEqual(writes(f).map(c=>[c.kind,c.id,c.state]),[['state','123','active']]);await reactivateGarmentPreview(p,f.read,f.deps.writeState,staged.inventoryFingerprint,true);assert.equal(writes(f).length,1)});
test('reactivation rejects absent approval, expired/draft/sold-out states and stale inventory',async()=>{for(const mutation of [f=>f.listing.state='draft',f=>f.listing.state='expired',f=>f.listing.state='sold_out',f=>f.inventory.products[0].offerings[0].quantity=1]){const {f,p}=await setup();const staged=await applyGarmentPreview(f.manifest,p,f.deps);mutation(f);f.calls.length=0;await assert.rejects(reactivateGarmentPreview(p,f.read,f.deps.writeState,staged.inventoryFingerprint,true));assert.equal(writes(f).length,0)}const {f,p}=await setup();const staged=await applyGarmentPreview(f.manifest,p,f.deps);f.calls.length=0;await assert.rejects(reactivateGarmentPreview(p,f.read,f.deps.writeState,staged.inventoryFingerprint,false),/confirmation/);assert.equal(writes(f).length,0)});

test('unchanged active source is provable even when retained-color target inventory is identical',async()=>{const f=fixture();f.input.targets=f.input.targets.slice(0,2);f.input.targets[1].color='Carbon Grey';const get=f.get;f.get=async(path,...args)=>{const r=await get(path,...args);if(path==='/products/variant/4012')r.result.variant.color='Carbon Grey';return r};const p=await buildGarmentPreview(f.manifest,f.input,9,f.read,f.get,'same-etsy-editions');p.expiresAt='2020-01-01';const target=await readMigrationTarget(p,f.read,'inspect');assert.equal(target.listing.state,'active');const classification=await classifyGarmentMigration(f.manifest,p,f.read);assert.equal(classification.kind,'SOURCE');assert.equal(classification.source.state,'GARMENT_MIGRATION_SOURCE_UNCHANGED');assert.equal(classification.source.inventoryFingerprint,p.beforeInventoryFingerprint);assert.equal(writes(f).length,0)});

test('source-first inspection still recognizes a genuinely staged inactive target',async()=>{const {f,p}=await setup();await applyGarmentPreview(f.manifest,p,f.deps);const c=await classifyGarmentMigration(f.manifest,p,f.read);assert.equal(c.kind,'TARGET');assert.equal(c.target.listing.state,'inactive')});
