import test from 'node:test';
import assert from 'node:assert/strict';
import {inspectListingImages,imagePlan,executeImageUpdate,imageUpdateSchema} from '../lib/warlock-commerce/listing-images.ts';
import {attachPostDraftImage} from '../lib/warlock-post-draft-images.ts';
const asset={id:'asset',role:'hero',contentType:'image/png',fileName:'hero.png'};
const listing={id:'listing',fulfillment:'PHYSICAL',etsyListingId:'123',assets:[]};
const manifest={id:'product',assets:[asset],listings:[listing],variants:[{retailPriceCents:4500,printfulVariantId:77}]};
function fixture(){let images=[{listing_id:123,listing_image_id:11,rank:1},{listing_id:123,listing_image_id:12,rank:2}];let uploads=0,saves=0,recorded;
 const read=async path=>path.endsWith('/images')?{count:images.length,results:images}:{listing_id:123,shop_id:99,state:'active',listing_type:'physical'};
 return {read,get uploads(){return uploads},get saves(){return saves},get recorded(){return recorded},set images(v){images=v},deps:{read,upload:async(a,rank,overwrite)=>{uploads++;assert.equal(a.id,'asset');assert.equal(overwrite,rank<=images.length);images=images.filter(i=>i.rank!==rank).concat({listing_id:123,listing_image_id:33,rank});return {listing_id:123,listing_image_id:33}},recordRemoteId:async id=>{recorded=id},save:async()=>{saves++}}};}
async function setup(){const f=fixture(),before=await inspectListingImages(listing,99,f.read);const input={productId:'product',fulfillment:'PHYSICAL',assetId:'asset',rank:1,expectedImageId:'11',expectedImagesFingerprint:before.imagesFingerprint,requestId:'request_123',confirmImageWrite:true};return {f,before,input};}
test('replacement verifies its slot and retains unrelated images and manifest',async()=>{const {f,before,input}=await setup(),original=structuredClone(manifest);const result=await executeImageUpdate(manifest,input,99,before,f.deps);assert.equal(result.state,'IMAGE_VERIFIED');assert.equal(f.recorded,'33');assert.equal(f.saves,1);assert.deepEqual(result.after.images,[{imageId:'33',rank:1},{imageId:'12',rank:2}]);assert.deepEqual(manifest,original)});
test('append requires next slot and uses overwrite false',async()=>{const {f,before,input}=await setup();Object.assign(input,{rank:3,expectedImageId:null});assert.equal((await executeImageUpdate(manifest,input,99,before,f.deps)).state,'IMAGE_VERIFIED');assert.equal(f.uploads,1)});
test('stale snapshot blocks upload',async()=>{const {f,before,input}=await setup();f.images=[];const result=await executeImageUpdate(manifest,input,99,before,f.deps);assert.equal(result.errorCode,'etsy_image_snapshot_changed');assert.equal(f.uploads,0)});
test('foreign assets, production files, wrong ranks and missing approval rejected',async()=>{const {before,input}=await setup();assert.throws(()=>imagePlan(manifest,{...input,assetId:'foreign'},before),/not_owned/);assert.throws(()=>imagePlan({...manifest,assets:[{...asset,role:'master'}]},input,before),/presentation_asset/);assert.throws(()=>imagePlan(manifest,{...input,rank:4,expectedImageId:null},before),/slot_changed/);assert.equal(imageUpdateSchema.safeParse({...input,confirmImageWrite:false}).success,false)});
test('recorded remote ID retries only verification after uncertain readback',async()=>{const {f,before,input}=await setup();const deps={...f.deps,save:async()=>{throw Error('database down')}};const first=await executeImageUpdate(manifest,input,99,before,deps);assert.equal(first.state,'NEEDS_REVIEW');assert.equal(first.remoteImageId,'33');assert.equal((await executeImageUpdate(manifest,input,99,before,f.deps,first.remoteImageId)).state,'IMAGE_VERIFIED');assert.equal(f.uploads,1)});
test('unrelated image changes fail readback and never save canonical link',async()=>{const {f,before,input}=await setup();const upload=f.deps.upload;f.deps.upload=async(...args)=>{const r=await upload(...args);f.images=[{listing_id:123,listing_image_id:33,rank:1},{listing_id:123,listing_image_id:44,rank:2}];return r};assert.equal((await executeImageUpdate(manifest,input,99,before,f.deps)).errorCode,'etsy_image_readback_mismatch');assert.equal(f.saves,0)});
test('inspection rejects foreign shop and incomplete image response',async()=>{const {f}=await setup();await assert.rejects(inspectListingImages(listing,100,f.read),/ownership_mismatch/);await assert.rejects(inspectListingImages(listing,99,async path=>path.endsWith('/images')?{count:1,results:[]}:f.read(path)),/incomplete/)});
test('post-draft staging only writes asset and journal; protected tables untouched',async()=>{const writes=[];const tx={$queryRaw:async()=>[],spellmarkListing:{findFirst:async()=>listing},spellmarkAsset:{findFirst:async()=>null,create:async({data})=>{writes.push('asset');return {id:'new',...data}}},spellmarkJournal:{upsert:async()=>writes.push('journal')}};const db={spellmarkProduct:{findUnique:async()=>({id:'product',title:'Vulpis',listings:[listing]})},$transaction:async fn=>fn(tx)};const files={read:async()=>({bytes:Buffer.from('png'),digest:'abc',contentType:'image/png'}),save:async()=>({...asset,pathname:'owned',blobUrl:'private',byteSize:3}),verify:async()=>{}};const input={productId:'product',role:'hero',fulfillment:'PHYSICAL',name:'hero.png',file:{file_id:'file_123',download_url:'https://files.oaiusercontent.com/hero.png',file_name:'hero.png'},confirmAttachment:true};const result=await attachPostDraftImage(input,db,files);assert.equal(result.state,'IMAGE_STAGED');assert.equal(result.etsyMutated,false);assert.deepEqual(writes,['asset','journal']);await assert.rejects(attachPostDraftImage({...input,role:'master'},db,files),/image_only/);await assert.rejects(attachPostDraftImage({...input,fulfillment:undefined},db,files),/fulfillment_required/)});
